name: ams-il-dev
services:
  next-app:
    container_name: next-app
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    # volumes:
    #   - ../:/app
    restart: unless-stopped
